# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://biicafe.github.io/"

# Google tracking id
google-tracking-id: False

#############
# HTML Head #
#############
lang: "en"
author: "Bii Cafe"
title: "Bii's Cafe"
description: "Welcome to Bii's Cafe."
keywords: "Bii Cafe"
favicon: "/img/favicon.ico"
################
# Header layout #
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
# 這邊可以加一些名言佳句，會在網頁上輪替顯示。
lines: # You can add HTML Tags in the Text
  - text: "大笨象會跳舞"
  - text: "小猴子會上樹"
  - text: "狐狸會翻跟斗 嘿"
  - text: "胖刺蝟會刷牙"
  - text: "貓頭鷹會喝咖啡"
me-img: "/img/jetpacktocat.png"
# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"
################
# Web app mode #
################
web-app-mode: True
# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
########
# Blog #
########
post-preview-words: 96
paginate: 8
email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False
# disqus-shortname: "personal-jekyll-theme"
syntax-highlight: True
############
# Timeline #
############
# 如果你需要換圖片，需要上傳圖片到這個資料庫裏面，然後 image 後面的雙引號內的路徑要做更改。 
events:
  - image: "/img/timeline/baracktocat.jpg"
    date: "Aug 2024 - Today"
    description: "事件二: 可以放一些班級紀錄。"
  - image: "/img/timeline/spidertocat.png"
    date: "Apr 2024 - Aug 2024"
    description: "事件一: 可以放一些班級紀錄。"
# First image of the Timeline
timeline-img: "/img/timeline/default.png"
###########
# Contact #
###########
email: "teacher.bii.cksh@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False
################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# 每篇分享文章下方，會有作者的簡介，所以看你想放甚麼，先幫你隨便寫一些。
# 圖片也可以改，一樣上傳到資料庫和改地址。
author_blurb:
  "成功高中國文科老師，人雖不聰明，但友善。"
author_blurb_image: "/img/author.png"
##################
# Social Buttons #
##################
social:
  - icon: "github"
    url: "https://biicafe.github.io"
  # - icon: "linkedin-in"
    # url: "https://www.linkedin.com"
  # - icon: "x-twitter"
    # url: "https://twitter.com/"
  # - icon: "rss"
    # url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"
  # - icon: "instagram"
  #   url: "https://www.instagram.com/yu_lin1226/"
############
# 404 page #
############
err-404-img: "/img/labtocat.png"
################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
